/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CMagazine : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CMagazine(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CMagazine obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CMagazine() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_CMagazine(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public CMagazine(CMagazineProfile Profile, CWeapon Weapon) : this(testPINVOKE.new_CMagazine(CMagazineProfile.getCPtr(Profile), CWeapon.getCPtr(Weapon)), true) {
    if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Fire(CPlayer Player, SWIGTYPE_p_Vector3 Direction) {
    bool ret = testPINVOKE.CMagazine_Fire(swigCPtr, CPlayer.getCPtr(Player), SWIGTYPE_p_Vector3.getCPtr(Direction));
    if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void RemoveProjectile(CProjectile Projectile) {
    testPINVOKE.CMagazine_RemoveProjectile(swigCPtr, CProjectile.getCPtr(Projectile));
  }

  public SWIGTYPE_p_VectorT_Core__CProjectile_p_t GetProjectiles() {
    SWIGTYPE_p_VectorT_Core__CProjectile_p_t ret = new SWIGTYPE_p_VectorT_Core__CProjectile_p_t(testPINVOKE.CMagazine_GetProjectiles(swigCPtr), false);
    return ret;
  }

}
