/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CVolumeObject : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CVolumeObject(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CVolumeObject obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CVolumeObject() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_CVolumeObject(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public void SetEnterFunc(SWIGTYPE_p_p_f_p_q_const__Core__Physics__CPhysicsProfile__void Func) {
    testPINVOKE.CVolumeObject_SetEnterFunc(swigCPtr, SWIGTYPE_p_p_f_p_q_const__Core__Physics__CPhysicsProfile__void.getCPtr(Func));
  }

  public void SetExitFunc(SWIGTYPE_p_p_f_p_q_const__Core__Physics__CPhysicsProfile__void Func) {
    testPINVOKE.CVolumeObject_SetExitFunc(swigCPtr, SWIGTYPE_p_p_f_p_q_const__Core__Physics__CPhysicsProfile__void.getCPtr(Func));
  }

  public virtual void SetPosition(SWIGTYPE_p_Vector3 Position) {
    testPINVOKE.CVolumeObject_SetPosition(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(Position));
    if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void RemoveVolume() {
    testPINVOKE.CVolumeObject_RemoveVolume(swigCPtr);
  }

}
