/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_BODY_TYPE {
  NONE = 0,
  BUILDING = 1 << 0,
  PLAYER = 1 << 1,
  GAME_OBJECT = 1 << 2,
  VEHICLE = 1 << 3,
  STATIC_GEOMETRY = 1 << 4,
  VOLUME = 1 << 5,
  TERRAIN = 1 << 6
}
