/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_DRIVER_TYPE {
  EDT_NULL = 0,
  EDT_DIRECT3D9 = 1,
  EDT_DIRECT3D10 = 2,
  EDT_OPENGL = 3,
  EDT_DIRECT3D11 = 4
}
