/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_PHYSICS_SHAPE {
  SHAPE_CUBE = 0,
  SHAPE_SPHERE = 1,
  SHAPE_CAPSULE = 2,
  SHAPE_CYLINDER = 3,
  SHAPE_CONE = 4,
  SHAPE_STATIC_TRIMESH = 5,
  SHAPE_TRIMESH = 6,
  SHAPE_PLANE = 7
}
