/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_PLAYER_STATE {
  EPS_IDLE = 0,
  EPS_DIEING = 1,
  EPS_DEAD = 2,
  EPS_RUNNING = 3,
  EPS_ATTACKING = 4,
  EPS_WAITING = 5,
  EPS_WALKING = 6,
  EPS_WANDERING = 7,
  EPS_EVADING = 8,
  EPS_SEEK_ENEMY = 9,
  EPS_SEEK_OBS = 10,
  EPS_SEEK_ITEM = 11,
  EPS_FIND_ENEMY = 12,
  EPS_DEFEND = 13,
  EPS_NONE = 14,
  EPS_COUNT = 15
}
