/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class GEO_SET_SUBSET : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GEO_SET_SUBSET(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GEO_SET_SUBSET obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GEO_SET_SUBSET() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_GEO_SET_SUBSET(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_Vector3 Position {
    set {
      testPINVOKE.GEO_SET_SUBSET_Position_set(swigCPtr, SWIGTYPE_p_Vector3.getCPtr(value));
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Vector3 ret = new SWIGTYPE_p_Vector3(testPINVOKE.GEO_SET_SUBSET_Position_get(swigCPtr), true);
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_Radian Yaw {
    set {
      testPINVOKE.GEO_SET_SUBSET_Yaw_set(swigCPtr, SWIGTYPE_p_Radian.getCPtr(value));
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Radian ret = new SWIGTYPE_p_Radian(testPINVOKE.GEO_SET_SUBSET_Yaw_get(swigCPtr), true);
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_f32 Scale {
    set {
      testPINVOKE.GEO_SET_SUBSET_Scale_set(swigCPtr, SWIGTYPE_p_f32.getCPtr(value));
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_f32 ret = new SWIGTYPE_p_f32(testPINVOKE.GEO_SET_SUBSET_Scale_get(swigCPtr), true);
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_void Data {
    set {
      testPINVOKE.GEO_SET_SUBSET_Data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = testPINVOKE.GEO_SET_SUBSET_Data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public GEO_SET_SUBSET() : this(testPINVOKE.new_GEO_SET_SUBSET__SWIG_0(), true) {
  }

  public GEO_SET_SUBSET(SWIGTYPE_p_Vector3 pos, SWIGTYPE_p_Radian yaw, SWIGTYPE_p_f32 scale, SWIGTYPE_p_void data) : this(testPINVOKE.new_GEO_SET_SUBSET__SWIG_1(SWIGTYPE_p_Vector3.getCPtr(pos), SWIGTYPE_p_Radian.getCPtr(yaw), SWIGTYPE_p_f32.getCPtr(scale), SWIGTYPE_p_void.getCPtr(data)), true) {
    if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
  }

  public GEO_SET_SUBSET(SWIGTYPE_p_Vector3 pos, SWIGTYPE_p_Radian yaw, SWIGTYPE_p_f32 scale) : this(testPINVOKE.new_GEO_SET_SUBSET__SWIG_2(SWIGTYPE_p_Vector3.getCPtr(pos), SWIGTYPE_p_Radian.getCPtr(yaw), SWIGTYPE_p_f32.getCPtr(scale)), true) {
    if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
  }

}
