/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum INVENTORY_TYPE {
  EIT_WEAPON,
  EIT_MAGAZINE,
  EIT_PROJECTILE,
  EIT_MELEE,
  EIT_TOOL
}
