/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PLAYER_INVENTORY : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PLAYER_INVENTORY(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(PLAYER_INVENTORY obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PLAYER_INVENTORY() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_PLAYER_INVENTORY(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_String ProfileName {
    set {
      testPINVOKE.PLAYER_INVENTORY_ProfileName_set(swigCPtr, SWIGTYPE_p_String.getCPtr(value));
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_String ret = new SWIGTYPE_p_String(testPINVOKE.PLAYER_INVENTORY_ProfileName_get(swigCPtr), true);
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool IsActive {
    set {
      testPINVOKE.PLAYER_INVENTORY_IsActive_set(swigCPtr, value);
    } 
    get {
      bool ret = testPINVOKE.PLAYER_INVENTORY_IsActive_get(swigCPtr);
      return ret;
    } 
  }

  public PLAYER_INVENTORY() : this(testPINVOKE.new_PLAYER_INVENTORY(), true) {
  }

}
