/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum SCENE_QUERY_FLAGS {
  SQF_NONE = 0,
  SQF_TERRAIN = 1 << 0,
  SQF_PLAYER = 1 << 1,
  SQF_INVENTORY_ITEM = 1 << 2,
  SQF_EDITOR = 1 << 3,
  SQF_OBSTACLE = 1 << 4,
  SQF_BUILDING = 1 << 5,
  SQF_VEHICLE = 1 << 6,
  SQF_EFFECT = 1 << 7,
  SQF_NAVMESH = 1 << 8,
  SQF_GAMEOBJECT = 1 << 9
}
