/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class TERRAIN_TYPE : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TERRAIN_TYPE(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TERRAIN_TYPE obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TERRAIN_TYPE() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_TERRAIN_TYPE(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public TERRAIN_TYPE.E_TERRAIN_TYPE TerrainType {
    set {
      testPINVOKE.TERRAIN_TYPE_TerrainType_set(swigCPtr, (int)value);
    } 
    get {
      TERRAIN_TYPE.E_TERRAIN_TYPE ret = (TERRAIN_TYPE.E_TERRAIN_TYPE)testPINVOKE.TERRAIN_TYPE_TerrainType_get(swigCPtr);
      return ret;
    } 
  }

  public TERRAIN_TYPE() : this(testPINVOKE.new_TERRAIN_TYPE(), true) {
  }

  public enum E_TERRAIN_TYPE {
    ETT_HEIGHT = 0,
    ETT_PAGED = 1,
    ETT_PLANE = 2
  }

}
