/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class test {
  public static readonly string LI_PROMPT = testPINVOKE.LI_PROMPT_get();
  public static readonly string LI_PROMPT2 = testPINVOKE.LI_PROMPT2_get();
  public static readonly string PLANE_ENTITY_NAME = testPINVOKE.PLANE_ENTITY_NAME_get();
  public static readonly string DEFAULT_PLANE_TERRAIN_MATERIAL = testPINVOKE.DEFAULT_PLANE_TERRAIN_MATERIAL_get();
}
