/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CPostEffect : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CPostEffect(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CPostEffect obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CPostEffect() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_CPostEffect(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void RegisterPostEffect() {
    testPINVOKE.CPostEffect_RegisterPostEffect(swigCPtr);
  }

  public void SetEnabled(bool flag) {
    testPINVOKE.CPostEffect_SetEnabled(swigCPtr, flag);
  }

  public string GetName() {
    string ret = testPINVOKE.CPostEffect_GetName(swigCPtr);
    return ret;
  }

}
