/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class CWeaponProfile : CItemProfile {
  private HandleRef swigCPtr;

  internal CWeaponProfile(IntPtr cPtr, bool cMemoryOwn) : base(testPINVOKE.CWeaponProfile_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(CWeaponProfile obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~CWeaponProfile() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          testPINVOKE.delete_CWeaponProfile(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public CWeaponProfile() : this(testPINVOKE.new_CWeaponProfile(), true) {
  }

  public bool isSemi {
    set {
      testPINVOKE.CWeaponProfile_isSemi_set(swigCPtr, value);
    } 
    get {
      bool ret = testPINVOKE.CWeaponProfile_isSemi_get(swigCPtr);
      return ret;
    } 
  }

  public bool isBurst {
    set {
      testPINVOKE.CWeaponProfile_isBurst_set(swigCPtr, value);
    } 
    get {
      bool ret = testPINVOKE.CWeaponProfile_isBurst_get(swigCPtr);
      return ret;
    } 
  }

  public bool isAuto {
    set {
      testPINVOKE.CWeaponProfile_isAuto_set(swigCPtr, value);
    } 
    get {
      bool ret = testPINVOKE.CWeaponProfile_isAuto_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_f32 Accuracy {
    set {
      testPINVOKE.CWeaponProfile_Accuracy_set(swigCPtr, SWIGTYPE_p_f32.getCPtr(value));
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_f32 ret = new SWIGTYPE_p_f32(testPINVOKE.CWeaponProfile_Accuracy_get(swigCPtr), true);
      if (testPINVOKE.SWIGPendingException.Pending) throw testPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public CMagazineProfile MagazineProfile {
    set {
      testPINVOKE.CWeaponProfile_MagazineProfile_set(swigCPtr, CMagazineProfile.getCPtr(value));
    } 
    get {
      IntPtr cPtr = testPINVOKE.CWeaponProfile_MagazineProfile_get(swigCPtr);
      CMagazineProfile ret = (cPtr == IntPtr.Zero) ? null : new CMagazineProfile(cPtr, false);
      return ret;
    } 
  }

}
