/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_ANIM_STATE {
  EAS_IDLE = 0,
  EAS_WALK = 1,
  EAS_RUN = 2,
  EAS_SPRINT = 3,
  EAS_DIEING = 4,
  EAS_DEAD = 5,
  EAS_CRAWL = 6,
  EAS_SHOOT = 7,
  EAS_RELOAD = 8,
  EAS_KNEEL = 9,
  EAS_PRONE = 10,
  EAS_RUNSHOOT = 11,
  EAS_HIT = 12,
  EAS_MELEE = 13,
  EAS_JUMP = 14,
  EAS_AIM_STAND = 15,
  EAS_CHANGE_ITEM = 16,
  EAS_NONE = 32
}
