/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_BUILDING_CATEGORY {
  EBC_SUPPLY = 0,
  EBC_TRAINING = 1,
  EBC_PROP = 2,
  EBC_DEFENCE = 3,
  EBC_OTHER = 4
}
