/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_CAMERA_MODE {
  ECM_CHASE = 0,
  ECM_FIXED = 1,
  ECM_FPS = 2,
  ECM_TOP_DOWN = 3,
  ECM_SIDE = 4,
  ECM_FREE = 5,
  ECM_GOD = 6,
  ECM_RTS = 7,
  ECM_SPRING = 8,
  ECM_CSS = 9,
  ECM_NONE = 10
}
