/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum E_PLAYER_TEAM {
  EPT_TEAM_1 = 0,
  EPT_TEAM_2 = 1,
  EPT_TEAM_3 = 2,
  EPT_TEAM_4 = 3,
  EPT_TEAM_5 = 4,
  EPT_TEAM_6 = 5,
  EPT_TEAM_7 = 6,
  EPT_TEAM_8 = 7,
  EPT_TEAM_9 = 8,
  EPT_TEAM_10 = 9,
  EPT_TEAM_COUNT = 10
}
