/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ENVIRONMENT_ATTRIBUTE_TYPE {
  EAT_NONE = 0,
  EAT_PICKUP = 1,
  EAT_DANGEROUS = 2,
  EAT_NEUTRAL = 3,
  EAT_MISSION = 4,
  EAT_UNKNOWN = 5,
  EAT_EDITOR = 6
}
