/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum ET_CAPABILITIES {
  ETC_BASIC_INFANTRY = 0,
  ETC_BASIC_ENGINEER = 1,
  ETC_BASIC_HTH_COMBAT = 2
}
